#!/usr/bin/evn python3
# -*- coding: utf-8 -*-
"""
Created on 3/23/20

@author waldo

A class used to report on access to buildings at Harvard. The AccessRec object holds information about a single
access, as reported by a line from the door access list provided by facilities.

"""

class AccessRec(object):
    def __init__(self, l):
        self.huid = l[3]
        self.building = l[6]
        self.date = l[1][:-5]
        self.time = l[1][-5:]
        self.who = l[2]
        self.entry = True

    def csvwrite(self):
        """
        Builds a list for the reports generated by process_access_list.py. The returned list will be a single line
        in an output .csv file
        :return: Information from the object in the order needed for the output .csv file
        """
        return([self.huid, self.who, self.building, self.date, self.time])